// Get Student Data type
export const STUDENT_DATA_PENDING = "STUDENT_DATA_PENDING";
export const STUDENT_DATA_FULFILLED = "STUDENT_DATA_FULFILLED";
export const STUDENT_DATA_REJECTED = "STUDENT_DATA_REJECTED";

// Delete Student Data Type
export const STUDENT_DELETE_PENDING = "STUDENT_DELETE_PENDING";
export const STUDENT_DELETE_FULFILLED = "STUDENT_DELETE_FULFILLED";
export const STUDENT_DELETE_REJECTED = "STUDENT_DELETE_REJECTED";

// Create Student Data
export const STUDENT_CREATE_PENDING = "STUDENT_CREATE_PENDING";
export const STUDENT_CREATE_FULFILLED = "STUDENT_CREATE_FULFILLED";
export const STUDENT_CREATE_REJECTED = "STUDENT_CREATE_REJECTED";

// Update Student Data
export const STUDENT_UPDATE_PENDING = "STUDENT_UPDATE_PENDING";
export const STUDENT_UPDATE_FULFILLED = "STUDENT_UPDATE_FULFILLED";
export const STUDENT_UPDATE_REJECTED = "STUDENT_UPDATE_REJECTED";
