// Get Student Data type
export const STUDENT_DATA_PENDING = "STUDENT_DATA_PENDING";
export const STUDENT_DATA_FULFILLED = "STUDENT_DATA_FULFILLED";
export const STUDENT_DATA_REJECTED = "STUDENT_DATA_REJECTED";

// Delete Student Data Type
export const STUDENT_DELETE_PENDING = "STUDENT_DELETE_PENDING";
export const STUDENT_DELETE_FULFILLED = "STUDENT_DELETE_FULFILLED";
export const STUDENT_DELETE_REJECTED = "STUDENT_DELETE_REJECTED";
